const Menu = [
  {
    id: "101",
    name: "Bread omlette",
    desc: "Our omelettes don’t just have fillings. They have toppings too!",
    tag: ["breakfast", "north-indian"],
    type: "non-veg",
    cost: 30,
    src: "./kalash_pics/Breakfast/Bread_omlette.jpg",
  },
  {
    id: "102",
    name: "Alu Paratha",
    desc: "Cuddle up with a plate of Aloo Parathas and you won't miss mommy anymore!",
    tag: ["breakfast", "north-indian"],
    type: "veg",
    cost: 45,
    src: "./kalash_pics/Breakfast/Alu_paratha.jpg",
  },
  {
    id: "103",
    name: "Bread Upma",
    desc: "They bring an instant smile on your face.",
    tag: ["breakfast", "south-indian"],
    type: "veg",
    cost: 50,
    src: "./kalash_pics/Breakfast/Bread_upma.jpg",
  },
  {
    id: "104",
    name: "Chicken 65",
    desc: "Food you like most is the food you eat most.",
    tag: ["breakfast", "north-indian", "top-picks"],
    type: "non-veg",
    cost: 90,
    src: "./kalash_pics/Breakfast/Chicken_65.jpg",
  },
  {
    id: "105",
    name: "Dosa",
    desc: "You can't wait to get home to them.",
    tag: ["breakfast", "south-indian"],
    type: "veg",
    cost: 50,
    src: "./kalash_pics/Breakfast/dosa.webp",
  },
  {
    id: "106",
    name: "Idli",
    desc: "Enjoy idli without guilt because it is so healthy.",
    tag: ["breakfast", "south-indian"],
    type: "veg",
    cost: 15,
    src: "./kalash_pics/Breakfast/idli.jfif",
  },
  {
    id: "107",
    name: "Litti Chokha",
    desc: " It is a completely different dish in terms of taste, texture and preparation",
    tag: ["breakfast", "north-indian", "top-picks"],
    type: "veg",
    cost: 80,
    src: "./kalash_pics/Breakfast/Litti_chokha.jfif",
  },
  {
    id: "108",
    name: "Onion Paratha",
    desc: "With baked onion and coriander chutney",
    tag: ["breakfast", "dinner", "north-indian"],
    type: "veg",
    cost: 50,
    src: "./kalash_pics/Breakfast/Onion_paratha.jfif",
  },
  {
    id: "109",
    name: "Paneer Paratha",
    desc: "Eat away at hunger.",
    tag: ["breakfast", "north-indian", "dinner", "top-picks"],
    type: "veg",
    cost: 60,
    src: "./kalash_pics/Breakfast/Paneer_paratha.jpg",
  },
  {
    id: "110",
    name: "Upma",
    desc: "Top notch south indian stuff at your home",
    tag: ["breakfast", "south-indian"],
    type: "veg",
    cost: 60,
    src: "./kalash_pics/Breakfast/Upma.jfif",
  },
  {
    id: "111",
    name: "Veg Sandwich",
    desc: "Fast Food for Fast Times.",
    tag: ["breakfast"],
    type: "veg",
    cost: 40,
    src: "./kalash_pics/Breakfast/Veg_sandwich.webp",
  },

  {
    id: "112",
    name: "Alu gobhi",
    desc: "Simple and healthy food with less masala",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 90,
    src: "./kalash_pics/Dinner/Alu_gobhi.webp",
  },
  {
    id: "113",
    name: "Bhindi masala",
    desc: "Finger licking ladyfingers",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 90,
    src: "./kalash_pics/Dinner/Bhindi_masala.jpg",
  },
  {
    id: "114",
    name: "Butter Chicken",
    desc: "Eat your chicken just how you like it",
    tag: ["lunch", "north-indian", "dinner", "top-picks"],
    type: "non-veg",
    cost: 230,
    src: "./kalash_pics/Dinner/Butter_chicken.jpg",
  },
  {
    id: "115",
    name: "Chicken Butter Masala",
    desc: "Masala butter chicken cooked to perfection",
    tag: ["lunch", "north-indian", "dinner"],
    type: "non-veg",
    cost: 210,
    src: "./kalash_pics/Dinner/Chicken_butter_masala.png",
  },
  {
    id: "116",
    name: "Chicken curry",
    desc: "Indian home style curry with traditional spices",
    tag: ["lunch", "north-indian", "dinner"],
    type: "non-veg",
    cost: 190,
    src: "./kalash_pics/Dinner/Chicken_curry.webp",
  },
  {
    id: "117",
    name: "Dum alu",
    desc: "The good old fashioned dum aloo",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 120,
    src: "./kalash_pics/Dinner/Dum_aloo.webp",
  },
  {
    id: "118",
    name: "Egg Curry",
    desc: "Real Food. Real Local.",
    tag: ["lunch", "north-indian", "dinner"],
    type: "non-veg",
    cost: 120,
    src: "./kalash_pics/Dinner/Egg_curry.jpg",
  },
  {
    id: "119",
    name: "Fish Curry",
    desc: "Mithila style fresh fish curry with herbs and spices",
    tag: ["lunch", "north-indian", "dinner"],
    type: "non-veg",
    cost: 190,
    src: "./kalash_pics/Dinner/Fish_curry.jpg",
  },
  {
    id: "120",
    name: "Malai Kofta",
    desc: "Made of paneer or cottage cheese, stuffed with dry fruits and a secret ingredient",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 210,
    src: "./kalash_pics/Dinner/Malai_kofta.jfif",
  },
  {
    id: "121",
    name: "Champaaran Meat",
    desc: "The essence of Bihar",
    tag: ["lunch", "north-indian", "dinner", "top-picks"],
    type: "non-veg",
    cost: 280,
    src: "./kalash_pics/Dinner/Mutton_curry.jpg",
  },
  {
    id: "122",
    name: "Paneer Butter Masala",
    desc: "Fresh and buttery paneer mixed with spices",
    tag: ["lunch", "north-indian", "dinner", "top-picks"],
    type: "veg",
    cost: 160,
    src: "./kalash_pics/Dinner/Paneer_butter_masala.jpg",
  },
  {
    id: "123",
    name: "Paneer Kadahai",
    desc: "The mughal style paneer kadahi",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 190,
    src: "./kalash_pics/Dinner/Paneer_kadai.jpg",
  },
  {
    id: "124",
    name: "Paneer chilli",
    desc: "The chinese style paneer containing 8 pieces",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 190,
    src: "./kalash_pics/Dinner/Panner_chilli.jpg",
  },
  {
    id: "125",
    name: "Raajma Masala",
    desc: "Be hungry for success the same way you are hungry for rajmaa chawal.",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 150,
    src: "./kalash_pics/Dinner/Raajma_masla.jpg",
  },
  {
    id: "126",
    name: "South Indian big meal",
    desc: "The pleasure of variety on your plate.",
    tag: ["lunch", "south-indian", "dinner", "top-picks"],
    type: "veg",
    cost: 290,
    src: "./kalash_pics/Dinner/Sout_indian_big_meal.jpg",
  },
  {
    id: "127",
    name: "South Indian lunch combo",
    desc: "From south to mouth.",
    tag: ["lunch", "south-indian"],
    type: "veg",
    cost: 290,
    src: "./kalash_pics/Dinner/South_indian_lunch_combo.jfif",
  },
  {
    id: "128",
    name: "South Indian meal",
    desc: "A taste of exotic India",
    tag: ["lunch", "south-indian", "dinner"],
    type: "veg",
    cost: 200,
    src: "./kalash_pics/Dinner/South_indian_meal.jfif",
  },
  {
    id: "129",
    name: "South Indian non veg Thali",
    desc: "A New Indian Experience",
    tag: ["lunch", "south-indian", "dinner", "top-picks"],
    type: "non-veg",
    cost: 290,
    src: "./kalash_pics/Dinner/South_indian_non_veg_thali.jpg",
  },
  {
    id: "130",
    name: "Chicken Biryani",
    desc: "Don't let anyone treat you like Upma,You're Biryani.",

    tag: ["lunch", "north-indian", "dinner", "top-picks"],
    type: "non-veg",
    cost: 210,
    src: "./kalash_pics/Dinner/Chicken_biryani.jpg",
  },
  {
    id: "131",
    name: "Egg biryani",
    desc: " If someone says true love doesn't exist, make them taste biryani.",
    tag: ["lunch", "north-indian", "dinner", "top-picks"],
    type: "non-veg",
    cost: 180,
    src: "./kalash_pics/Dinner/Egg_biryani.webp",
  },
  {
    id: "132",
    name: "Veg paneer Biryani",
    desc: "When life gives you a thousand reasons to cry, show life that you got biryani to smile.",
    tag: ["lunch", "north-indian", "dinner", "top-picks"],
    type: "veg",
    cost: 210,
    src: "./kalash_pics/Dinner/Veg_biryani.jpg",
  },

  {
    id: "133",
    name: "Roti",
    desc: "Round and completely baked",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 10,
    src: "./kalash_pics/Dinner/Roti.jpg",
  },
  {
    id: "134",
    name: "Butter Naan",
    desc: "Food you like most is the food you eat most.",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 25,
    src: "./kalash_pics/Dinner/Naan.webp",
  },
  {
    id: "135",
    name: "Jeera rice",
    desc: "What intense deliciousness!",
    tag: ["lunch", "north-indian", "dinner"],
    type: "veg",
    cost: 70,
    src: "./kalash_pics/Dinner/Jeera_rice.jpg",
  },
  {
    id: "136",
    name: "Kulcha",
    desc: "Food you like most is the food you eat most.",
    tag: ["lunch", "north-indian", "dinner", "top-picks"],
    type: "veg",
    cost: 30,
    src: "./kalash_pics/Breakfast/Kulcha.webp",
  },
];
export default Menu;
